version: '3.0'
services:
    nats:
        image: nats-streaming
        ports:
            - 4222:4222
    libsbox:
        build:
            context: ./tools
            dockerfile: libsbox/Dockerfile
        privileged: true
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/sandbox
            - data:/data
    invoker:
        build:
            context: ./tools
            dockerfile: invoker/Dockerfile
        environment:
            NATS_SERVER: nats://nats:4222
            SANDBOX_DIR: /sandbox
            DATA_DIR: /data
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/sandbox
            - data:/data
        depends_on:
            - nats
    packagebuilder:
        build:
            context: ./tools
            dockerfile: packagebuilder/Dockerfile
        environment:
            NATS_SERVER: nats://nats:4222
            SANDBOX_DIR: /sandbox
            DATA_DIR: /data
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/sandbox
            - data:/data
        depends_on:
            - nats
    app:
        build: .
        ports:
            - 3013:3013
        environment:
            NATS_SERVER: nats://nats:4222
            MAIL_PASSWORD: Fedroadmin
            DATA_DIR: /fejudge/data
        volumes:
            - data:/fejudge/data
        depends_on:
            - nats
volumes:
    libsboxd:
    sandbox:
    data:
        driver: local
        driver_opts:
            type: none
            device: $PWD/data
            o: bind
