version: '3.0'
services:
    nats:
        image: nats
        ports:
            - 4222:4222
    libsbox:
        build:
            context: invoker/libsbox/
        privileged: true
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/invoker/sandbox
            - data:/data
    invoker:
        build:
            context: invoker/
        environment:
            NATS_SERVER: nats://nats:4222
            DATA_DIR: /data
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/invoker/sandbox
            - data:/data
        depends_on:
            - nats
    app:
        build: .
        ports:
            - 3013:3013
        environment:
            MAIL_USERNAME: fejudge.system@gmail.com
            MAIL_PASSWORD: secret # You will never guess!
            FLASK_APP: app
            FLASK_ENV: development
            FLASK_DEBUG: 0
            NATS_SERVER: nats://nats:4222
            DATA_DIR: /data
        volumes:
            - data:/data
        depends_on:
            - nats
volumes:
    libsboxd:
    sandbox:
    data:
        driver: local
        driver_opts:
            type: none
            device: $PWD/data
            o: bind
