version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        logging: 
            driver: none
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        depends_on: 
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: judge:1:1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        logging: 
            driver: none
    libsbox:
        image: libsbox
        privileged: true
        volumes:
            - /etc/libsboxd:/etc/libsboxd
            - /tmp/invoker/submission:/invoker/submission
    fejudge:
        image: fejudge
        ports: 
            - 3013:3013
            - 3113:3113
        environment:
            KAFKA_SERVER: kafka:9092
            MAIL_PASSWORD: Fedroadmin
    invoker:
        image: invoker
        environment: 
            KAFKA_SERVER: kafka:9092
            JUDGE_SERVER: fejudge:3113
        volumes:
            - /etc/libsboxd:/etc/libsboxd
            - /tmp/invoker/submission:/invoker/submission
