version: '3.0'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: judge:1:1,packages:1:1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    libsbox:
        build:
            context: ./tools
            dockerfile: libsbox/Dockerfile
        privileged: true
        volumes:
            - libsboxd:/etc/libsboxd
            - libsbox:/tools/invoker/libsbox
            - libsbox:/tools/packagebuilder/libsbox
            - data:/tools/invoker/data
    invoker:
        build: 
            context: ./tools
            dockerfile: invoker/Dockerfile
        environment: 
            KAFKA_SERVER: kafka:9092
        volumes:
            - libsboxd:/etc/libsboxd
            - libsbox:/tools/invoker/libsbox
            - data:/tools/invoker/data
    packagebuilder:
        build:
            context: ./tools
            dockerfile: packagebuilder/Dockerfile
        environment: 
            KAFKA_SERVER: kafka:9092
        volumes:
            - libsboxd:/etc/libsboxd
            - libsbox:/tools/packagebuilder/libsbox
            - data:/tools/packagebuilder/data
    app:
        build: .
        ports: 
            - 3013:3013
        environment:
            KAFKA_SERVER: kafka:9092
            MAIL_PASSWORD: Fedroadmin
        volumes:
            - data:/fejudge/data
volumes:
    libsboxd:
    libsbox:
    data:
