version: '3.0'
services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181
        logging: 
            driver: none
    kafka:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        depends_on: 
            - zookeeper
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: judge:1:1,packages:1:1
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        logging: 
            driver: none
    libsbox:
        build: ./libsbox
        privileged: true
        volumes:
            - libsboxd:/etc/libsboxd
            - submission:/tools/invoker/submission
            - data:/tools/invoker/data
    invoker:
        build: 
            context: ./tools
            dockerfile: docker-files/Dockerfile_invoker
        environment: 
            KAFKA_SERVER: kafka:9092
        volumes:
            - libsboxd:/etc/libsboxd
            - submission:/tools/invoker/submission
            - data:/tools/invoker/data
    packagebuilder:
        build:
            context: ./tools
            dockerfile: docker-files/Dockerfile_packagebuilder
        environment: 
            KAFKA_SERVER: kafka:9092
        volumes:
            - libsboxd:/etc/libsboxd
            - data:/tools/invoker/data
    fejudge:
        build: .
        ports: 
            - 3013:3013
        environment:
            KAFKA_SERVER: kafka:9092
            MAIL_PASSWORD: Fedroadmin
        volumes:
            - data:/fejudge/data
volumes:
    libsboxd:
    submission:
    data:
