version: '3'
services:
    nats:
        image: nats
        ports:
            - 4222:4222
    app:
        build: .
        ports:
            - 3013:3013
        environment:
            - MAIL_USERNAME=${MAIL_USERNAME}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
            - FLASK_APP=app
            - FLASK_ENV=development
            - FLASK_DEBUG=0
            - NATS_SERVER=nats://nats:4222
            - DATA_DIR=/data
        volumes:
            - data:/data
        depends_on:
            - nats
    libsbox:
        build:
            context: invoker/libsbox/
        privileged: true
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/invoker/sandbox
            - data:/data
    invoker:
        build:
            context: invoker/
        environment:
            - PYTHONUNBUFFERED=1
            - SOCKETIO_SERVER=http://app:3013
            - NATS_SERVER=nats://nats:4222
            - DATA_DIR=/data
        volumes:
            - libsboxd:/etc/libsboxd
            - sandbox:/invoker/sandbox
            - data:/data
        depends_on:
            - app
            - libsbox
volumes:
    libsboxd:
    sandbox:
    data:
        driver: local
        driver_opts:
            type: none
            device: $PWD/data
            o: bind
