"""empty message

Revision ID: 0c1df8cf45a8
Revises: 526f9ee2c16f
Create Date: 2020-03-23 16:42:02.763194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1df8cf45a8'
down_revision = '526f9ee2c16f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DATETIME(),
               type_=sa.Interval(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=128), nullable=True))
        batch_op.drop_column('second_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('last_name')

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Interval(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
