"""empty message

Revision ID: 1c12c49fd59b
Revises: 3f234484d970
Create Date: 2019-12-26 22:14:59.201696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c12c49fd59b'
down_revision = '3f234484d970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.DATETIME(),
               type_=sa.Interval(),
               existing_nullable=True)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.Text(), nullable=True))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.TEXT(), nullable=True))
        batch_op.drop_column('source')

    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Interval(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
