"""empty message

Revision ID: 37fc317ae18b
Revises: 
Create Date: 2020-01-29 14:20:25.130073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37fc317ae18b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest')),
    sa.UniqueConstraint('name', name=op.f('uq_contest_name'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('avatar', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('active_language', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('contest_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name=op.f('fk_contest_request_contest_id_contest')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_contest_request_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contest_request'))
    )
    op.create_table('problem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('problem_type', sa.String(length=16), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('max_submissions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name=op.f('fk_problem_contest_id_contest')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_problem'))
    )
    op.create_table('restore_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_restore_token_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restore_token'))
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], name=op.f('fk_submission_contest_id_contest')),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], name=op.f('fk_submission_problem_id_problem')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_submission_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('restore_token')
    op.drop_table('problem')
    op.drop_table('contest_request')
    op.drop_table('user')
    op.drop_table('contest')
    # ### end Alembic commands ###
