"""empty message

Revision ID: 553af4a5dc21
Revises: 204a09a2b978
Create Date: 2020-03-25 22:37:41.054415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553af4a5dc21'
down_revision = '204a09a2b978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('contest', schema=None) as batch_op:
    #     batch_op.alter_column('duration',
    #            existing_type=sa.DATETIME(),
    #            type_=sa.Interval(),
    #            existing_nullable=True)

    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('status')

    # with op.batch_alter_table('contest', schema=None) as batch_op:
    #     batch_op.alter_column('duration',
    #            existing_type=sa.Interval(),
    #            type_=sa.DATETIME(),
    #            existing_nullable=True)

    # ### end Alembic commands ###
