"""empty message

Revision ID: 887d91731810
Revises: ed8aff2eecec
Create Date: 2020-07-09 22:07:57.990293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887d91731810'
down_revision = 'ed8aff2eecec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('names', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problem', schema=None) as batch_op:
        batch_op.drop_column('names')

    # ### end Alembic commands ###
