"""empty message

Revision ID: a0eee40b6479
Revises: b51d68f840ce
Create Date: 2020-07-22 16:41:10.063927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0eee40b6479'
down_revision = 'b51d68f840ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restore_token')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=64), nullable=True))

    op.create_table('restore_token',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_restore_token_user_id_user'),
    sa.PrimaryKeyConstraint('id', name='pk_restore_token')
    )
    # ### end Alembic commands ###
